basic/controllers/TaskController.php
<?php

namespace app\controllers;


use app\models\WorkWhithDB;
use Faker\Provider\DateTime;
use Psr\Log\InvalidArgumentException;
use yii\web\Controller;
use app\models\CreateTaskModel;
use yii;
use yii\base\Exception;
use yii\i18n\Formatter;


class TaskController extends Controller
{

    public function actionIndex()
    {
        $query = WorkWhithDB::find()->all();
        return $this->render('index', ['tasks' => $query]);
    }


   /*public function actionCreate()
   {
       $task = TaskModel::createTask();
       if($task->load(Yii::$app->request->post()) && $task->validate()) {
           $date = time();
           $task->create_date = $date;
           $task->save();
           Yii::$app->session->setFlash('success', 'Данные сохранены');
           return $this->refresh();
       }
       return $this->render('create', ['task' => $task]);
   }*/

   public function actionCreate()
   {
       $task = new CreateTaskModel();
       $flag = $task->load(Yii::$app->request->post());

       if($flag) {

           $task->createTask();
           Yii::$app->session->setFlash('success', 'Данные сохранены');
           return $this->refresh();
       }
       return $this->render('create', ['task' => $task]);
   }




    public function actionUpdate($id)
    {
        $task = new CreateTaskModel();
        $task->load(Yii::$app->request->post());
        if(!$task) {
            $date = time();
            $task->create_date = $date;
            $task->save();
            Yii::$app->session->setFlash('success', 'Данные обновлены');
            return $this->refresh();
        }
        return $this->render('update', ['task' => $task]);
/*
        $this->blaBlaBla ($id, 'Данные обновлены', 'update');*/


    }




   /* public function blaBlaBla ($id, $textMessage, $renderingView) {

        $task = TaskModel::findOne($id);
        if($task->load(Yii::$app->request->post())) {
            $date = time();
            $task->create_date = $date;
            $task->save();
            Yii::$app->session->setFlash('success', $textMessage);
            return $this->refresh();
        }
        return $this->render($renderingView, ['task' => $task]);
    }*/





    public function actionDelete($id)
    {
        TaskModel::findOne($id)->delete();
        return $this->redirect('index');
    }

    public function actionComplete($id)
    {
        $task = TaskModel::findOne($id);
        $task->complete_date = time();
        $task->save();
        return $this->redirect('index');
    }

   public function actionTask($id)
   {
        $task = TaskModel::findOne($id);
        return $this->render('task', ['task'=> $task]);
   }





   public static function readVar($var)
   {
       echo '<pre>';
       print_r($var);
       echo '</pre>';
       die;
   }
}

basic/views/task/create.php
<?php

/* @var $this yii\web\View */
/* @var $task app\models\CreateTaskModel */

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

echo $url = Yii::$app->urlManager->createUrl(['task/create']);
$this->title =  $url;


$this->params['breadcrumbs'][] = $this->title;
?>

<div class="task-index">
<a href="<?php echo Url::to(['task/index'])?>" class="aLinkGeneralPage"">На главную</a>
<?php /*echo '<pre>'. print_r($task).'<pre>'; exit()*/?>

<?php $form = ActiveForm::begin(); ?>
<?php echo $form->field($task, 'name'); ?>
<?php echo $form->field($task, 'short_description'); ?>
<?php echo $form->field($task, 'full_description')->textarea(); ?>
<?php echo HTML::submitButton('Сохранить задание', ['class'=> 'btn aLinkGeneralPage']); ?>
<?php ActiveForm::end() ?>



</div>

basic/views/task/create2.php
<?php

/* @var $this yii\web\View */
/* @var $task app\models\TaskModel */

use yii\helpers\Url;

echo $url = Yii::$app->urlManager->createUrl(['task/create']);
$this->title =  $url;


$this->params['breadcrumbs'][] = $this->title;
?>

<?php
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
?>
<div class="task-index">
<a href="<?php echo Url::to(['task/index'])?>" class="aLinkGeneralPage"">На главную</a>
<?php /*echo '<pre>'. print_r($task).'<pre>'; exit()*/?>

<?php $form = ActiveForm::begin(); ?>
<?php echo $form->field($task, 'name'); ?>
<?php echo $form->field($task, 'short_description'); ?>
<?php echo $form->field($task, 'full_description')->textarea(); ?>
<?php echo HTML::submitButton('Сохранить задание', ['class'=> 'btn aLinkGeneralPage']); ?>
<?php ActiveForm::end() ?>



</div>

basic/views/task/index.php
<?php

/* @var $this yii\web\View */
/* @var $tasks app\models\TaskModel*/


use yii\helpers\Url;


echo $url = Yii::$app->urlManager->createUrl(['task/index']);
$this->title =  $url;

?>

<div class="task-index">

    <?php $this->params['breadcrumbs'][] = $this->title; ?>

    <h1>Все задания</h1>

    <a href="<?php echo Url::to(['task/create'])?>" class="aLinkGeneralPage">
        Create New Task
    </a>

    <div class="taskContainer">
        <div class="task">
            <div class="taskHeader">
                <div class="taskId">ID</div>
                <div class="taskName">Name</div>
                <div class="taskShortDescr">Краткое описание</div>
                <div class="taskCreateDate">Дата создания</div>
                <div class="taskCompleteDate">Дата выполнения</div>
                <div class="tasknavigateButton">Вспомогательные кнопки</div>
            </div>
            <?php
                foreach ($tasks as $elem) { ?>
                    <div class="taskContent">

                        <div class="taskId">
                            <?php echo $elem->id?>
                        </div>

                        <div class="taskName">
                            <!--<a href="<?php /*echo Url::to(['task/task', 'id' => $elem->id])*/?>"><?php /*echo $elem->name*/?></a>-->
                            <a href="<?php echo Url::to(['task', 'id' => $elem->id])?>"><?php echo $elem->name?></a>
                        </div>

                        <div class="taskShortDescr">
                            <?php echo $elem->short_description?>
                        </div>

                        <div class="taskCreateDate">
                            <?php echo Yii::$app->formatter->format($elem->create_date, 'datetime');?>
                        </div>

                        <div class="taskCompleteDate">
                            <?php echo Yii::$app->formatter->format($elem->complete_date, 'datetime'?'datetime':'nullDisplay') ?>
                        </div>


                        <div class="tasknavigateButton">

                            <form action="<?php echo Url::to(['task/update'])?>" method="GET">
                                <input type="submit" value="Update"  class="aLinkGeneralPage">
                                <input type="hidden" name="id" value="<?php echo $elem->id?>">
                            </form>

                            <!--<form action="<?php /*echo Url::to(['task/delete'])*/?>" method="GET" >-->
                            <form action="delete" method="GET" >
                                <input type="submit" value="Delete" class="aLinkGeneralPage">
                                <input type="hidden" name="id" value="<?php echo $elem->id?>">
                            </form>

                            <form action="<?php echo Url::to(['task/complete'])?>" method="GET" >
                                <input type="submit" value="Complite" class="aLinkGeneralPage">
                                <input type="hidden" name="id" value="<?php echo $elem->id?>">
                            </form>

                        </div>

                    </div>
                <?php }?>
        </div>
    </div>
</div>

basic/views/task/task.php
<?php

/*@var $task  app\models\TaskModel*/


echo $url = Yii::$app->urlManager->createUrl(['task/index']);
$this->title =  $url;
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="task-index">
    <h1>Полное описание задания: <?php echo $task->name ?></h1>

<p class="fullDescr">
    <?php echo $task->full_description?$task->full_description: 'Описание отсутствует...'?>
<div>
    <p>Когда создан:
        <?php echo Yii::$app->formatter->format($task->create_date, 'datetime');  ?>
    </p>

    <p>Когда выполнен:
        <?php echo Yii::$app->formatter->format($task->complete_date, 'datetime'?'datetime': ' Активен ') ?>
    </p>
</div>
<p>
    <span>
         <a href="<?php echo Yii::$app->urlManager->createUrl(['task/index'])?>" class="aLinkGeneralPage">Назад&nbsp;</a>
        <a href="<?php echo Yii::$app->urlManager->createUrl(['task/update']).'?id='.$task->id?>" class="aLinkGeneralPage">Обновить&nbsp;</a>
        <a href="<?php echo Yii::$app->urlManager->createUrl(['task/delete']).'?id='.$task->id?>" class="aLinkGeneralPage">Удалить&nbsp;</a>
        <a href="<?php echo Yii::$app->urlManager->createUrl(['task/complete']).'?id='.$task->id?>" class="aLinkGeneralPage">Завершить&nbsp;</a>
    </span>
</p>
</div>

basic/views/task/update.php
<?php


/* @var $this yii\web\View */
/* @var $task app\models\TaskModel */


echo $url = Yii::$app->urlManager->createUrl(['task/index']);
$this->title =  $url;
$this->params['breadcrumbs'][] = $this->title;
?>

<h1>Update Task</h1>

<?php
    use yii\helpers\Url;
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
?>

<div class="task-index">
<a href="<?php echo Url::to(['task/index'])?>" class="aLinkGeneralPage">На главную</a>


<?php $form = ActiveForm::begin(); ?>
<?php echo $form->field($task, 'name'); ?>
<?php echo $form->field($task, 'short_description'); ?>
<?php echo $form->field($task, 'full_description')->textarea(); ?>
<?php echo HTML::submitButton('Update', ['class'=> 'btn btn-primary']); ?>
<?php ActiveForm::end() ?>

</div>